# Generated by Django 4.0 on 2021-12-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id_class', models.AutoField(primary_key=True, serialize=False, verbose_name='id_class')),
                ('number', models.IntegerField()),
                ('letter', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_stud', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('id_class', models.ForeignKey(db_column='id_class', on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.schoolclass')),
            ],
        ),
    ]
